# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfa576fea1d7bf60d63613b1a6a370d782a716eea117b27acf68b6ad02dfd639ff1776ce865401ef460096b4087803966bb2e4b198dff9559a5732ebbf30e8d4

test:
  secret_key_base: 0d445f1921d478bc9012aed0f0359ce73e1c02a2caa366b9e1afe82b5da67bc3316cadad6c7699f1651509e2ad1a4ba8cd873e02d81fbce1e4bd188d282a7d98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
